global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: 'prometheus'
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 'localhost:9090'

- job_name: 'inventory'
  # Override the global default and scrape targets from this job every 5 seconds.
  honor_timestamps: true
  scrape_interval: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - 'inventory-service:8080'

- job_name: 'locust'
  # Override the global default and scrape targets from this job every 5 seconds.
  honor_timestamps: true
  scrape_interval: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - 'locust:8089'

- job_name: 'node-exporter'
  # Override the global default and scrape targets from this job every 5 seconds.
  honor_timestamps: true
  scrape_interval: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - 'node-exporter:9100'

- job_name: 'postgresql-exporter'
  # Override the global default and scrape targets from this job every 5 seconds.
  honor_timestamps: true
  scrape_interval: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - 'postgres-exporter:9187'

